export { showResult, hideResult } from './result/resultActions'
export { saveYear } from './year/yearActions'
export { saveMonth } from './month/monthActions'
export { saveDay } from './day/dayActions'
export { random, personalCode } from './random/randomActions'